{"name": "verify login successfully", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'C:\\\\Automation\\\\Hackaton python\\\\Hackathon-Python\\\\screen-shots\\\\screen2021-12-28 17:48:30.png'", "trace": "self = <Test.test_web.Test_web object at 0x000001BF8A46E4A0>, username = 'Allie2', password = 's3cret'\n\n    @allure.title(\"verify login successfully\")\n    @allure.description(\"This test verify that multiple users have successfully logged on to the site\")\n    @pytest.mark.parametrize(\"username,password\", DDT.write_to_list_from_csv())\n    def test_03(self, username, password):\n>       Web_WF.login(username, password)\n\ntest_web.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\Main\\WorkFlows\\web_wf.py:30: in login\n    Common_Ops.attach_file()\n..\\Main\\Utilities\\common_ops.py:33: in attach_file\n    allure.attach.file(image, attachment_type=allure.attachment_type.PNG)\n..\\venv\\lib\\site-packages\\allure_commons\\_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n..\\venv\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n..\\venv\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n..\\venv\\lib\\site-packages\\allure_pytest\\listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n..\\venv\\lib\\site-packages\\allure_commons\\reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n..\\venv\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n..\\venv\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n..\\venv\\lib\\site-packages\\allure_commons\\logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\nC:\\Users\\jondi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\shutil.py:434: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = 'C:\\\\Automation\\\\Hackaton python\\\\Hackathon-Python\\\\screen-shots\\\\screen2021-12-28 17:48:30.png'\ndst = 'C:\\\\Automation\\\\Hackaton python\\\\Hackathon-Python\\\\allure-results\\\\bf2645a9-df57-406c-bc6b-1ae1f1ef52cc-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           OSError: [Errno 22] Invalid argument: 'C:\\\\Automation\\\\Hackaton python\\\\Hackathon-Python\\\\screen-shots\\\\screen2021-12-28 17:48:30.png'\n\nC:\\Users\\jondi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\shutil.py:254: OSError"}, "description": "This test verify that multiple users have successfully logged on to the site", "steps": [{"name": "login to the web", "status": "broken", "statusDetails": {"message": "OSError: [Errno 22] Invalid argument: 'C:\\\\Automation\\\\Hackaton python\\\\Hackathon-Python\\\\screen-shots\\\\screen2021-12-28 17:48:30.png'\n", "trace": "  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Automation\\Hackaton python\\Hackathon-Python\\Main\\WorkFlows\\web_wf.py\", line 30, in login\n    Common_Ops.attach_file()\n  File \"C:\\Automation\\Hackaton python\\Hackathon-Python\\Main\\Utilities\\common_ops.py\", line 33, in attach_file\n    allure.attach.file(image, attachment_type=allure.attachment_type.PNG)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 182, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\allure_pytest\\listener.py\", line 226, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\allure_commons\\reporter.py\", line 114, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\automation\\hackaton python\\hackathon-python\\venv\\lib\\site-packages\\allure_commons\\logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"C:\\Users\\jondi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\shutil.py\", line 434, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"C:\\Users\\jondi\\AppData\\Local\\Programs\\Python\\Python310\\lib\\shutil.py\", line 254, in copyfile\n    with open(src, 'rb') as fsrc:\n"}, "attachments": [{"source": "bf2645a9-df57-406c-bc6b-1ae1f1ef52cc-attachment.png", "type": "image/png"}], "parameters": [{"name": "username", "value": "'Allie2'"}, {"name": "password", "value": "'s3cret'"}], "start": 1640706510399, "stop": 1640706510499}], "parameters": [{"name": "username", "value": "'Allie2'"}, {"name": "password", "value": "'s3cret'"}], "start": 1640706510399, "stop": 1640706510500, "uuid": "bf96ed1e-d89c-44d6-9373-85d0b9091e6a", "historyId": "8599e824ebd03d8632cfda0f93f2ef10", "testCaseId": "baf6a1382796f07c9dc773c5aa09940f", "fullName": "Test.test_web.Test_web#test_03", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web')"}, {"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "Test_web"}, {"name": "host", "value": "Jondi"}, {"name": "thread", "value": "13332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_web"}]}